server:
  port: 2020

mybatis:
  mapper-locations: classpath:/sql/*Mapper.xml
  type-aliases-package: com.zyq.domain.*

spring:
  datasource:
    username: root
    password: 401120719
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zyq?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
  thymeleaf:
    prefix: classpath:/templates/